=== Zanobos/xmlschema-showcase/showcase1/dtd/nffgInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- author a.zanotti -->

<!ELEMENT NffgVerifier ((Nffg*), (Policy*))>

<!ELEMENT Nffg (UpdateTime, (Node*), (Link*))>
<!ATTLIST Nffg
                name ID #REQUIRED
>

<!ELEMENT UpdateTime (#PCDATA)>

<!ELEMENT Node (Functionality)>
<!ATTLIST Node
                name ID #REQUIRED
                links IDREFS #IMPLIED
>

<!ELEMENT Functionality EMPTY>
<!ATTLIST Functionality
                        func (CACHE|DPI|FW|MAIL_CLIENT|MAIL_SERVER|NAT|SPAM|VPN|WEB_CLIENT|WEB_SERVER) #REQUIRED
>

<!ELEMENT Link EMPTY>
<!ATTLIST Link
                name ID #REQUIRED
                sourceNode IDREF #REQUIRED
                destNode IDREF #REQUIRED
>

<!ELEMENT Policy (VerificationResult, (Functionality*))>
<!ATTLIST Policy
                name ID #REQUIRED
                sourceNode IDREF #REQUIRED
                destNode IDREF #REQUIRED
                positive (true|false) #REQUIRED
>

<!ELEMENT VerificationResult (Result, Message, VerificationTime)>
<!ELEMENT Result EMPTY>
<!ATTLIST Result
                res (true|false) #REQUIRED
>

<!ELEMENT Message (#PCDATA)>
<!ELEMENT VerificationTime (#PCDATA)>

=== Zanobos/xmlschema-showcase/DP2_Assign1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="windows-1252"?>
<!--
 author a.zanotti
-->

<!DOCTYPE NffgVerifier SYSTEM "nffgInfo.dtd">
<NffgVerifier>
    <Nffg name="NFFG0">
        <UpdateTime>2016-09-27T12:54:20.000+02:00</UpdateTime>
        <Node name="WEBSERVER0" links="Link0">
            <Functionality func="WEB_SERVER"/>
        </Node>
        <Node name="WEBCLIENT0" links="Link1">
            <Functionality func="WEB_CLIENT"/>
        </Node>
        <Node name="NAT0" links="Link0 Link1">
            <Functionality func="NAT"/>
        </Node>
        <Link name="Link0" sourceNode="WEBSERVER0" destNode="NAT0"/>
        <Link name="Link1" sourceNode="NAT0" destNode="WEBCLIENT0"/>
    </Nffg>
    <Policy name="policy0" sourceNode="WEBSERVER0" destNode="WEBCLIENT0" positive="true">
        <VerificationResult>
            <Result res="true"/>
            <Message>Policy verification result true</Message>
            <VerificationTime>2016-09-26T03:19:20.000+02:00</VerificationTime>
        </VerificationResult>
    </Policy>
</NffgVerifier>
